[versions]
agp = "8.4.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.12.0"
jargon2Api = "1.1.1"
jargon2ApiVersion = "1.5.0"
bcprovJdk15on = "1.70"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
jargon2-api = { group = "com.kosprov.jargon2", name = "jargon2-api", version.ref = "jargon2Api" }
lambdaworks-jargon2-api = { group = "com.lambdaworks", name = "jargon2-api", version.ref = "jargon2ApiVersion" }
bcprov-jdk15on = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bcprovJdk15on" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

